services:
  web-nginx:
    image: nginx:latest
    ports:
      - "90:80"
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: exampledb
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepass

        



